version: "3.7"

services:
  mysql:
    #Name has to be mysql for network host to resolve properly
    image: mysql:5.7
    networks:
      - todo-app
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  todo-app:
    image: node:12-alpine
    networks:
      - todo-app
    working_dir: /app
    volumes:
      - ./:/app # Note the use of relative path
    environment:
      MYSQL_HOST: mysql #use the mysql service name
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    ports:
      - 3000:3000
    command: sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"

# Ensure network is created dynamically by docker compose
networks:
  todo-app:

    # Ensure volume is created dynamically by docker compose
volumes:
  todo-mysql-data:
